// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pyrtqeuaxonvfanpdpjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5cnRxZXVheG9udmZhbnBkcGp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0OTI4NzgsImV4cCI6MjA3NDA2ODg3OH0.lQSKygdFMIswz9pmvWtNKL65k76FVJg8QCpIjjp2SYQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});